trigger:
  - master

pool:tansen-poko

stages:
  - stage: Build
    jobs:
      - job: FirstJob
        steps:
          - bash: echo Build FirstJob
          - bash: echo $(PipelineLevelVariable)
          - bash: echo $(Build.BuildNumber)
          - bash: echo $(Build.BuildId)
          - bash: echo $(Build.SourceBranchName)
          - bash: echo $(Build.SourcesDirectory)
          - bash: echo $(System.DefaultWorkingDirectory)
          - bash: ls -R $(System.DefaultWorkingDirectory)
          - bash: echo $(Build.ArtifactStagingDirectory)
          - bash: java -version
          - bash: node --version
          - bash: python --version
          - bash: mvn -version