# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool: my poko laptop

jobs:
  - job: Job1
    steps:
      - script: Hello world
        displayName: "this is for first job"
      - script: |
          echo here we are running more than one script so the | is present.
          echo second script
          echo third script
        displayName: "this is for second job"
  - job: Job2
    dependsOn: Job1
    steps:
      - script: echo Job2 script 1 and it's depends on first job!
        displayName: "this is the display name of job2"
  - job: Job3
    dependsOn: Job1
    steps:
      - script: echo Job3 script 1 depends on job 1
        displayName: "this is for second job"
  - job: Job4
    dependsOn:
      - Job2
      - Job3
    steps:
      - script: echo Job4 script 1 it's depends on job2 and job3
        displayName: "job4 script 1"
